---
- name: Docker Configuration
  hosts: all
  become: true
  connection: ssh
  tasks:
    - name: Update apt package index
      command: sudo apt update

    - name: Install Docker
      apt:
        name: docker.io
        state: present
      become: true

    - name: Start Docker Service
      service:
        name: docker
        state: started
        enabled: yes
      become: true

    - name: Deploy Docker Container
      docker_container:
        name: finance-me
        image: shrathan/banking:v1
        state: started
        ports:
          - "8005:8005"

