---
- name: Docker
  hosts: all
  become: yes
  connection: ssh
  tasks:
    - name: Update apt package index
      command: sudo apt update
  
    - name: Install Docker engine
      apt:
        name: docker.io
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
      become: yes

    - name: Pull Docker application image
      docker_image:
        name: shrathan/banking:v1
        source: pull
        state: present

    - name: Run Docker container
      docker_container:
        name: finance
        image: shrathan/banking:v1
        state: started
        restart_policy: always
        ports:
          - "8005:8005"  
